apiVersion: v1
kind: Pod
metadata:
  name: hello-mysql
  namespace: hello-kube
  labels:
    app: hello-mysql
spec:
  containers:
  - name: hello-mysql-container
    image: mysql:latest
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: master
    - name: MYSQL_DATABASE
      value: hello_mysql
  restartPolicy: Always