apiVersion: apps/v1
kind: Deployment
metadata:
  name:  webapp-mysql
  namespace: hello-kube
  labels:
    app:  webapp-mysql
spec:
  selector:
    matchLabels:
      app: webapp-mysql
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: webapp-mysql
    spec:
      containers:
      - name:  webapp-mysql
        image:  nginx
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi