apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello-world-rs-nginx
  labels:
    app: hello-world-rs-nginx
    type: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-rs-nginx
      type: frontend
  template:
    metadata:
      labels:
        app: hello-world-rs-nginx
        type: frontend
    spec:
      containers:
      - name: hello-world-rs-nginx
        image: nginx
        ports:
        - name: web
          containerPort:  80
          protocol: TCP